### ISSUE TITLE
News widget does not appear in landing page

### ISSUE THREAD

**Issue by nirlipo** [icaps25/icaps25.github.io#23]
Right windows panel does not appear in https://icaps25.icaps-conference.org/ but appears only if you click in home link, which takes you to: https://icaps25.icaps-conference.org/home/

**Comment by nirlipo** [comment]
@dharabor The only fix I can think of is to ask that the DNS https://icaps25.icaps-conference.org/ points to https://icaps25.icaps-conference.org/home/ 

I'm not sure how to change it otherwise. I think [this is where you specify](https://github.com/icaps25/icaps25.github.io/blob/main/config.toml#L19) where it should be shown and this is[ hugo's documentation.](https://gohugo.io/methods/site/mainsections/)

**Comment by dharabor** [comment]
Do you mean the news sidebar? that's working as intended. Only on the homepage. for the other pages we have more space for content.

I tried it the other way, with a global sidebar, but it seemed worse

--
https://harabor.net/daniel

-------- Original Message --------

**Comment by dharabor** [comment]
Oh, I see what you mean. OK, on it.

**Comment by dharabor** [comment]
Submitted a PR for this one
https://github.com/icaps25/icaps25.github.io/pull/24

We had a small mis-configuration of the theme.

**Comment by dharabor** [comment]
To add a bit more detail: Hugo has two options for enabling the news sidebar. 
(1) Via the site-wide `config.toml`
(2) Via the frontmatter of the relevant page `sidebar: recent`

I set option (2) but was missing (1). It's weird because the same content page is parsed no matter how it is accessed. Based on my current understanding, I feel this is a borderline bug in Hugo.

**Comment by nirlipo** [comment]
Awesome! Great detective work :)
